### ISSUE TITLE
Week 3 and 4 Scrum Report

### ISSUE THREAD

**Issue by jason0770** [VexMihir/chessApp#12]
Name: Jason Lai
CSID: p9v2b
Scrum Reports:

What did you work on this past iteration (2 weeks)?
1. Attended meetings with Alex and discussed the UI components and Theme.
2. Completely Implemented the.RoomAssignment Component, and InGameView Component, 
3. Collaborated with Alex and worked together to implement the PreviousMoveList Component  
4. Mainly focused on implementing the Chessboard Component.
5. Presented a frontend demo for Project Progress 2.
6. Research Drag and Drop API for Chessboard.
7. Learned React.
Notes: The UI parts do not have the functionality and logic. They are just prototypes.  

What were any major issues/challenges you ran into?
1. Did not understand the lifecycle of a React component. It caused that the app does not pass the strict mode.
2. Had to implement the app without directly accessing the DOM by utilizing the useState, or other React hooks, I learned how to implement the app in React thinking
3. Had a hard time to implement the Drag and Drop API because I am only familiar with the Click event handler.
4. Had to realize that the scope of a child component cannot directly communicate with another child component.
5. Did not understand Redux because I am familiar with MVC.
6. Had a hard time to implement the logic of the chessboard.

What do you plan to work on for this coming iteration (2 weeks)?
1. enhance my React knowledge.
2. learn Node Express
3. try to implement my app with Tailwind rather than pure CSS.
4. understand and implement the app with Redux
5. try to fix the app in order to pass the strict mode
6. try to complete the logic of the chessboard 
7. try to achieve this minimal requirement -  Allowing people to play Chess games over the internet

**Comment by AlexNgGit** [comment]
Alex Nguyen
b7e6r

What did you work on this past iteration (2 weeks)?

Attended meetings with Jason and discussed the UI components and Theme.
Implemented the PrevMoveList component
Present the portion of PrevMoveList

What were any major issues/challenges you ran into?
Was sick entire week


What do you plan to work on for this coming iteration (2 weeks)?
Starting implementing the functionalities of buttons between chessboards and prevmovelist
Look into socket and start to figure out recuders' structure in order to pass data around

**Comment by wallstarr** [comment]
Dan Blustein
i5v2b

What did you work on this past iteration (2 weeks)?
Mainly investigation into Socket.io and learning Socket.io. I now have functionality that allows users to create rooms (at the moment these are just socket rooms) and have other users "join" the room via a socket call. 

What were any major issues/challenges you ran into?
Not particularly -- it was just a minor struggle to learn Socket.io, but otherwise I think I am getting the hang of it. 

What do you plan to work on for this coming iteration (2 weeks)?
Working on the functionality to create unique URL's which lead to a single live game. Its integration with the front end will be a primary focus.

**Comment by VexMihir** [comment]
Mihir Bhandari
s5z2b

What did you work on this past iteration (2 weeks)?
Mainly investigating and learning Socket.io. Working on implementing the room system with @wallstarr. Finalizing the broader picture of how the frontend is going to look and finalizing the styling with Jason and Alex

What were any major issues/challenges you ran into?
Nothing in particular as we haven't really dived into the complicated parts of the app at this stage.

What do you plan to work on for this coming iteration (2 weeks)?
Working to implement and tie up the chess.js package with the chessboard.js frontend package as well as finish the room functionality. Brainstorm ideas on how to incorporate redux into the app.

**Comment by kdang243** [comment]
Kevin Dang
q7x2b

What did you work on this past iteration (2 weeks)?
Researched the chess.js package in detail and created an abstraction of the chess.js package that is more tailored to the need of our project. Enabling the frontend to call the chess.js backend more efficiently. Furthermore, I investigated how we could store the state of each chess game in our backend in order to allow users to replay the chess games and view moves that were made.

What were any major issues/challenges you ran into?
No major issues this week, everything went quite smoothly on my end as chess.js is a very well made package with lots of documentation.

What do you plan to work on for this coming iteration (2 weeks)?
I plan to work with mihir as he is responsible for integrating our back and frontend together. Assisting with the chess.js backend in particular. Furthermore, I am planning to look into how mongoDB can be used to store FEN notation for the replaying of chess games.
