### ISSUE TITLE
Scrum Report W9-10

### ISSUE THREAD

**Issue by VexMihir** [VexMihir/chessApp#26]

**Comment by VexMihir** [comment]
Name: Mihir Bhandari
csid: s5z2b

What did you work on this past iteration (3 weeks)?

Cleaning up code on the backend.
Adding error handling to ensure our server doesn't crash.
Deployment to render. 
What were any major issues/challenges you ran into?

None in particular.
What do you plan to work on for this coming sprint?

Finishing up the project by polishing and refining our website.
Revamping our frontend by choosing a new color palette and adding animations if time persists.
Updating the readme and preparing for the upcoming demo

**Comment by kdang243** [comment]
Name: Kevin Dang
csid: q7x2b

What did you work on this past iteration (3 weeks)?

Deployed both front and backend to render successfully. 
Identified bugs within the main branch that was deployed to render.

What were any major issues/challenges you ran into?

Some communication issues within the team but was resolved in a timely manner. 
Ran into some issues with the initial deployment as our backend was hooked up to localhost and not the deployed backend initially.

What do you plan to work on for this coming sprint?

Adding finishing touches to the frontend as well as review all our goals, ensuring they are met and the team is satisfied.
Updating the readme and preparing for the upcoming demo.

**Comment by jason0770** [comment]
Name: Jason Lai
csid: p9v2b

What did you work on this past iteration (2 weeks)?
1. I was working on the in-game view UI including both the chessboard and sideboard.
2. I tried to understand the code written by my teammates.
3. I asked my teammates what I need.

What were any major issues/challenges you ran into?
1. I would like to have a global state for Socket.io so that every component can invoke it easily and the app can avoid prop drilling.
2. I have not fully understood the mechanism of Socket.io networking handling and have not fully figured out how to handle the Socket.io networking issues.
3. I did not realize that multiplayer's UI view is different from each other until I work on this project or Socket.io.

What do you plan to work on for this coming sprint?
1. Need to fix the issue: After the user clicks the rewatch button at the Game Outcome modal result on In-game view, the user cannot be directed to the right previous move page with the correct data.
2. Improve RoomAssignment functionality and make sure the frontend can receive a list of room numbers and will modify the database and add corresponding RESTful GET API.
3. Add the login system and will add the User collection to MongoDB
4. Add ELO system and make the corresponding changes to MongoDB and Backend RESTful API code.
5. Change the main page of the app if I add both 1. single mode (Human vs Computer) and 2. multiplayer mode if possible. Need to research how I can finish this. Will explore if any NPM package is available before deciding if I need to implement the chess logic locally.
6. Refactor the frontend and backend code if I know the solutions and Fix any frontend and backend bugs if found

**Comment by AlexNgGit** [comment]
Name: Alex
csid: b7e6r

What did you work on this past iteration (3 weeks)?

- Add error handlings and a quick research on stockfish


What were any major issues/challenges you ran into?

- No particular problem. Live, Laugh Love all weeks. 

- Maybe that styling is still a pain (I am not familiar with CSS).


What do you plan to work on for this coming sprint?

- Finish AI feature.
- Cleaning up my code.

**Comment by wallstarr** [comment]
Name: Dan Blustein
csid: i5v2b

What did you work on this past iteration (3 weeks)?

Adding backend functionality (resignation, offered draws) to support live game view stuff.
Refactoring backend logic.
Deploying project to render. 

What were any major issues/challenges you ran into?
Not many, though it was difficult to coordinate changes with frontend, as frontend needed changes from backend that were difficult to understand/resolve. It ended up working out, and we now have the fundamental functionality to work off of.

What do you plan to work on for this coming sprint?
Fixing bugs in backend, and polishing up certain backend features like disconnects to be more smooth.
